server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb;create=true
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/master.yaml
  h2:
    console:
      enabled: true
